create table public.likes (
    id bigint generated by default as identity not null primary key,
    created_at timestamp with time zone not null default now(),
    user_id uuid not null default auth.uid (),
    article_id bigint not null,

    constraint unique_article_like unique (user_id, article_id),
    constraint likes_article_id_fkey foreign key (article_id) references articles (id),
    constraint likes_user_id_fkey foreign key (user_id) references auth.users (id)
);

alter table public.likes enable row level security;

create policy "Enable delete for users based on user_id"
on public.likes
to public
using (
  (( SELECT auth.uid() AS uid) = user_id)
);

create policy "Enable insert for authenticated users only"
on public.likes
to authenticated
with check (
  true
);

create policy "Enable read access for all users"
on public.likes
to authenticated
using (
  true
);