create table "public"."views" (
    "id" bigint generated by default as identity  primary key,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);

alter table "public"."views" enable row level security;

create policy "Enable read access for authenticated users"
on "public"."views"
as permissive
for select
to authenticated
using (true);



