create table public.articles (
    id bigint generated by default as identity not null primary key,
    created_at timestamp with time zone not null default now(),
    title text not null,
    content text not null,
    author text null
);

alter table public.articles enable row level security;

create policy "Enable read access for all users"
on public.articles
to authenticated
using (
  true
);

alter publication supabase_realtime add table articles;