-- Extension required for auto-populating updated_at column as part of below trigger
create extension if not exists moddatetime schema extensions;

create type Status as enum (
  'OPEN',
  'IN_PROGRESS',
  'CLOSED'
);

create table public.issues (
    id bigint generated by default as identity not null primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone,
    user_id uuid not null default auth.uid (),
    title text not null,
    description text not null,
    status Status default 'OPEN' not null,

    constraint issues_user_id_fkey foreign key (user_id) references auth.users (id)
);

-- Uses Moddatetime extension to auto-populated updated_at column
create trigger handle_updated_at before update on public.issues
  for each row execute procedure moddatetime (updated_at);
  

alter table public.issues enable row level security;

create policy "Enable delete for users based on user_id"
on public.issues
to public
using (
  (( SELECT auth.uid() AS uid) = user_id)
);

create policy "Enable insert for authenticated users only"
on public.issues
to authenticated
with check (
  true
);

create policy "Enable read access for authenticated users only"
on public.issues
to authenticated
using (
  true
);